TEMPLATE = app
CONFIG += console c++17
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
    ..\metier\Subject.cpp \
    Controller.cpp \
        Main.cpp\
         View.cpp \
    ..\metier\Board.cpp \
    ..\metier\BoardLoader.cpp \
    ..\metier\Element.cpp \
    ..\metier\Game.cpp \
    ..\metier\Position.cpp \
    ..\metier\Square.cpp \


HEADERS += \
    ..\metier\Subject.h \
    Controller.h \
    Controller.h \
    View.h \
    ..\metier\Baba.h \
    ..\metier\Baba_Text.h \
    ..\metier\Best_Text.h \
    ..\metier\Board.h \
    ..\metier\BoardLoader.h \
    ..\metier\Bone.h \
    ..\metier\Direction.h \
    ..\metier\Element.h \
    ..\metier\ElementType.h \
    ..\metier\Element_Is_Kill.h \
    ..\metier\Element_Is_Push.h \
    ..\metier\Element_Is_Sink.h \
    ..\metier\Element_Is_Stop.h \
    ..\metier\Element_Is_Win.h \
    ..\metier\Element_Is_You.h \
    ..\metier\Flag.h \
    ..\metier\Flag_Text.h \
    ..\metier\Game.h \
    ..\metier\GameRule.h \
    ..\metier\Grass.h \
    ..\metier\Grass_Text.h \
    ..\metier\Is.h \
    ..\metier\Kill.h \
    ..\metier\Lava.h \
    ..\metier\Lava_Text.h \
    ..\metier\Metal.h \
    ..\metier\Metal_Text.h \
    ..\metier\Observer.h \
    ..\metier\Position.h \
    ..\metier\Push.h \
    ..\metier\Rock.h \
    ..\metier\Rock_Text.h \
    ..\metier\Sink.h \
    ..\metier\Square.h \
    ..\metier\Stop.h \
    ..\metier\Wall.h \
    ..\metier\Wall_Text.h \
    ..\metier\Water.h \
    ..\metier\Water_Text.h \
    ..\metier\Win.h \
    ..\metier\You.h \
    ..\metier\elements\Baba.h \
    ..\metier\elements\Baba_Text.h \
    ..\metier\elements\Best_Text.h \
    ..\metier\elements\Bone.h \
    ..\metier\elements\Flag.h \
    ..\metier\elements\Flag_Text.h \
    ..\metier\elements\Grass.h \
    ..\metier\elements\Grass_Text.h \
    ..\metier\elements\Is.h \
    ..\metier\elements\Kill.h \
    ..\metier\elements\Lava.h \
    ..\metier\elements\Lava_Text.h \
    ..\metier\elements\Metal.h \
    ..\metier\elements\Metal_Text.h \
    ..\metier\elements\Push.h \
    ..\metier\elements\Rock.h \
    ..\metier\elements\Rock_Text.h \
    ..\metier\elements\Sink.h \
    ..\metier\elements\Stop.h \
    ..\metier\elements\Wall.h \
    ..\metier\elements\Wall_Text.h \
    ..\metier\elements\Water.h \
    ..\metier\elements\Water_Text.h \
    ..\metier\elements\Win.h \
    ..\metier\elements\You.h \


HEADERS += \
    ..\metier\Subject.h \
    Controller.h \
    View.h \
    ..\metier\Baba.h \
    ..\metier\Baba_Text.h \
    ..\metier\Best_Text.h \
    ..\metier\Board.h \
    ..\metier\BoardLoader.h \
    ..\metier\Bone.h \
    ..\metier\Direction.h \
    ..\metier\Element.h \
    ..\metier\ElementType.h \
    ..\metier\Element_Is_Kill.h \
    ..\metier\Element_Is_Push.h \
    ..\metier\Element_Is_Sink.h \
    ..\metier\Element_Is_Stop.h \
    ..\metier\Element_Is_Win.h \
    ..\metier\Element_Is_You.h \
    ..\metier\Flag.h \
    ..\metier\Flag_Text.h \
    ..\metier\Game.h \
    ..\metier\GameRule.h \
    ..\metier\Grass.h \
    ..\metier\Grass_Text.h \
    ..\metier\Is.h \
    ..\metier\Kill.h \
    ..\metier\Lava.h \
    ..\metier\Lava_Text.h \
    ..\metier\Metal.h \
    ..\metier\Metal_Text.h \
    ..\metier\Observer.h \
    ..\metier\Position.h \
    ..\metier\Push.h \
    ..\metier\Rock.h \
    ..\metier\Rock_Text.h \
    ..\metier\Sink.h \
    ..\metier\Square.h \
    ..\metier\Stop.h \
    ..\metier\Wall.h \
    ..\metier\Wall_Text.h \
    ..\metier\Water.h \
    ..\metier\Water_Text.h \
    ..\metier\Win.h \
    ..\metier\You.h \
    ..\metier\elements\Baba.h \
    ..\metier\elements\Baba_Text.h \
    ..\metier\elements\Best_Text.h \
    ..\metier\elements\Bone.h \
    ..\metier\elements\Flag.h \
    ..\metier\elements\Flag_Text.h \
    ..\metier\elements\Grass.h \
    ..\metier\elements\Grass_Text.h \
    ..\metier\elements\Is.h \
    ..\metier\elements\Kill.h \
    ..\metier\elements\Lava.h \
    ..\metier\elements\Lava_Text.h \
    ..\metier\elements\Metal.h \
    ..\metier\elements\Metal_Text.h \
    ..\metier\elements\Push.h \
    ..\metier\elements\Rock.h \
    ..\metier\elements\Rock_Text.h \
    ..\metier\elements\Sink.h \
    ..\metier\elements\Stop.h \
    ..\metier\elements\Wall.h \
    ..\metier\elements\Wall_Text.h \
    ..\metier\elements\Water.h \
    ..\metier\elements\Water_Text.h \
    ..\metier\elements\Win.h \
    ..\metier\elements\You.h \


HEADERS += \
    ..\metier\Subject.h \
    Controller.h \
    View.h \
    ..\metier\Baba.h \
    ..\metier\Baba_Text.h \
    ..\metier\Best_Text.h \
    ..\metier\Board.h \
    ..\metier\BoardLoader.h \
    ..\metier\Bone.h \
    ..\metier\Direction.h \
    ..\metier\Element.h \
    ..\metier\ElementType.h \
    ..\metier\Element_Is_Kill.h \
    ..\metier\Element_Is_Push.h \
    ..\metier\Element_Is_Sink.h \
    ..\metier\Element_Is_Stop.h \
    ..\metier\Element_Is_Win.h \
    ..\metier\Element_Is_You.h \
    ..\metier\Flag.h \
    ..\metier\Flag_Text.h \
    ..\metier\Game.h \
    ..\metier\GameRule.h \
    ..\metier\Grass.h \
    ..\metier\Grass_Text.h \
    ..\metier\Is.h \
    ..\metier\Kill.h \
    ..\metier\Lava.h \
    ..\metier\Lava_Text.h \
    ..\metier\Metal.h \
    ..\metier\Metal_Text.h \
    ..\metier\Observer.h \
    ..\metier\Position.h \
    ..\metier\Push.h \
    ..\metier\Rock.h \
    ..\metier\Rock_Text.h \
    ..\metier\Sink.h \
    ..\metier\Square.h \
    ..\metier\Stop.h \
    ..\metier\Wall.h \
    ..\metier\Wall_Text.h \
    ..\metier\Water.h \
    ..\metier\Water_Text.h \
    ..\metier\Win.h \
    ..\metier\You.h \
    ..\metier\elements\Baba.h \
    ..\metier\elements\Baba_Text.h \
    ..\metier\elements\Best_Text.h \
    ..\metier\elements\Bone.h \
    ..\metier\elements\Flag.h \
    ..\metier\elements\Flag_Text.h \
    ..\metier\elements\Grass.h \
    ..\metier\elements\Grass_Text.h \
    ..\metier\elements\Is.h \
    ..\metier\elements\Kill.h \
    ..\metier\elements\Lava.h \
    ..\metier\elements\Lava_Text.h \
    ..\metier\elements\Metal.h \
    ..\metier\elements\Metal_Text.h \
    ..\metier\elements\Push.h \
    ..\metier\elements\Rock.h \
    ..\metier\elements\Rock_Text.h \
    ..\metier\elements\Sink.h \
    ..\metier\elements\Stop.h \
    ..\metier\elements\Wall.h \
    ..\metier\elements\Wall_Text.h \
    ..\metier\elements\Water.h \
    ..\metier\elements\Water_Text.h \
    ..\metier\elements\Win.h \
    ..\metier\elements\You.h \


HEADERS += \
    ..\metier\Subject.h \
    Controller.h \
    View.h \
    ..\metier\Baba.h \
    ..\metier\Baba_Text.h \
    ..\metier\Best_Text.h \
    ..\metier\Board.h \
    ..\metier\BoardLoader.h \
    ..\metier\Bone.h \
    ..\metier\Direction.h \
    ..\metier\Element.h \
    ..\metier\ElementType.h \
    ..\metier\Element_Is_Kill.h \
    ..\metier\Element_Is_Push.h \
    ..\metier\Element_Is_Sink.h \
    ..\metier\Element_Is_Stop.h \
    ..\metier\Element_Is_Win.h \
    ..\metier\Element_Is_You.h \
    ..\metier\Flag.h \
    ..\metier\Flag_Text.h \
    ..\metier\Game.h \
    ..\metier\GameRule.h \
    ..\metier\Grass.h \
    ..\metier\Grass_Text.h \
    ..\metier\Is.h \
    ..\metier\Kill.h \
    ..\metier\Lava.h \
    ..\metier\Lava_Text.h \
    ..\metier\Metal.h \
    ..\metier\Metal_Text.h \
    ..\metier\Observer.h \
    ..\metier\Position.h \
    ..\metier\Push.h \
    ..\metier\Rock.h \
    ..\metier\Rock_Text.h \
    ..\metier\Sink.h \
    ..\metier\Square.h \
    ..\metier\Stop.h \
    ..\metier\Wall.h \
    ..\metier\Wall_Text.h \
    ..\metier\Water.h \
    ..\metier\Water_Text.h \
    ..\metier\Win.h \
    ..\metier\You.h \
    ..\metier\elements\Baba.h \
    ..\metier\elements\Baba_Text.h \
    ..\metier\elements\Best_Text.h \
    ..\metier\elements\Bone.h \
    ..\metier\elements\Flag.h \
    ..\metier\elements\Flag_Text.h \
    ..\metier\elements\Grass.h \
    ..\metier\elements\Grass_Text.h \
    ..\metier\elements\Is.h \
    ..\metier\elements\Kill.h \
    ..\metier\elements\Lava.h \
    ..\metier\elements\Lava_Text.h \
    ..\metier\elements\Metal.h \
    ..\metier\elements\Metal_Text.h \
    ..\metier\elements\Push.h \
    ..\metier\elements\Rock.h \
    ..\metier\elements\Rock_Text.h \
    ..\metier\elements\Sink.h \
    ..\metier\elements\Stop.h \
    ..\metier\elements\Wall.h \
    ..\metier\elements\Wall_Text.h \
    ..\metier\elements\Water.h \
    ..\metier\elements\Water_Text.h \
    ..\metier\elements\Win.h \
    ..\metier\elements\You.h \
